export const MEDIA_QUERY_FEATURE_KEYS = [
  "type",
  "minWidth",
  "maxWidth",
  "width",
  "height",
  "minHeight",
  "maxHeight",
  "aspectRatio",
  "minAspectRatio",
  "maxAspectRatio",
  "orientation",
  "resolutionValue",
  "minResolution",
  "maxResolution",
  "hover",
  "anyHover",
  "pointer",
  "anyPointer",
  "update",
  "colorScheme",
  "reducedMotion",
  "reducedData",
  "contrast",
  "forcedColors",
  "colorGamut",
  "dynamicRange",
  "invertedColors",
  "scripting",
  "overflowBlock",
  "overflowInline",
  "customFeatures",
] as const;

export type MediaQueryFeatureKey = typeof MEDIA_QUERY_FEATURE_KEYS[number];
