// NOTE: This file is being refactored in phases to use a shared
// `runCoreTests` helper defined in tests/runtime/core/core.shared.ts. If you
// need to restore the original single-environment layout, use README.md.bak
// and the git history for reference.
import {
  assertCondition,
  assertMatchingUnits,
  assertPercentMeasurement,
  assertUnit,
  getErrorConfig,
  hasCssMethod,
  isMeasurement,
  isPercentMeasurement,
  m,
  makeUnitAssert,
  makeUnitGuard,
  makeUnitHelper,
  makeUnitHelperFromDefinition,
  mCm,
  mCqh,
  mCqw,
  mDeg,
  mDpi,
  mDvw,
  measurementMax,
  measurementMin,
  measurementUnitMetadata,
  mEm,
  mFr,
  mKhz,
  mLvw,
  mMs,
  mPercent,
  mPx,
  mSvw,
  mVh,
  setErrorConfig,
} from '../../../src';
import type { CoreApi } from './core.shared';
import { runCoreTests } from './core.shared';

const api = {
  m,
  mPercent,
  mPx,
  mCm,
  mEm,
  mVh,
  mSvw,
  mLvw,
  mDvw,
  mCqh,
  mDeg,
  mMs,
  mKhz,
  mDpi,
  mFr,
  mCqw,
  assertMatchingUnits,
  assertUnit,
  assertCondition,
  isMeasurement,
  isPercentMeasurement,
  assertPercentMeasurement,
  makeUnitHelper,
  makeUnitHelperFromDefinition,
  measurementUnitMetadata,
  makeUnitAssert,
  makeUnitGuard,
  hasCssMethod,
  measurementMin,
  measurementMax,
  setErrorConfig,
  getErrorConfig,
} as unknown as CoreApi;

runCoreTests('src', api);
